
# The first line of this file MUST be the project_id
project_id = "rigurrwjiaucodxuuzeh"

[api]
# The API will be available at http://localhost:54321
port = 54321
# You can define a custom schema for your API. Defaults to "public".
schemas = ["public", "storage", "graphql"]
# You can add extra search paths for your API. Defaults to "public".
extra_search_path = ["public"]
# The maximum number of rows returns from a view, table, or function. Defaults to 1000.
max_rows = 1000

[db]
# The database will be available at postgresql://postgres:postgres@localhost:54322/postgres
port = 54322
# You can use a custom major version of PostgreSQL. Defaults to 15.
major_version = 15

[studio]
# The Studio will be available at http://localhost:54323
port = 54323

# Email testing server.
[inbucket]
# The SMTP server will be available at localhost:54324
port = 54324
# The web UI will be available at http://localhost:54325
ui_port = 54325

[functions.public-questions]
# verify_jwt = true

[functions.questions-crud]
# verify_jwt = true

[functions.create-organization]
# verify_jwt = true

[functions.submit-feedback]
# verify_jwt = true

[functions.handle-sms-webhook]
verify_jwt = false

[functions.update-sms-settings]
# verify_jwt = true

[functions.api-questions]
# verify_jwt = true

[functions.api-feedback]
# verify_jwt = true
