
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'organization-service'
    static_configs:
      - targets: ['organization-service:3002']

  - job_name: 'feedback-service'
    static_configs:
      - targets: ['feedback-service:3003']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3004']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3005']

  - job_name: 'sms-service'
    static_configs:
      - targets: ['sms-service:3006']

  - job_name: 'asset-service'
    static_configs:
      - targets: ['asset-service:3007']
